# Generated by Django 4.2.11 on 2026-05-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_generatedletter_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedletter',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
